groundingdino:
  config_file: "scenecomplete/modules/GroundedSegmentAnything/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py"
  checkpoint: "scenecomplete/modules/weights/groundingdino_swint_ogc.pth"
  box_threshold: 0.3
  text_threshold: 0.25

sam:
  version: "vit_h"
  checkpoint: "scenecomplete/modules/weights/sam_vit_h_4b8939.pth"

device: "cuda"